name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Checkout
      uses: actions/checkout@v4


    - name: Extract Git version tag
      id: vars
      run: echo ::set-output name=version::$(git describe --tags --always)

    - name: Build
      run: |
        VERSION=${{ steps.vars.outputs.version }}
        docker build . --file Dockerfile --tag docker.io/${{ vars.DOCKER_USERNAME }}/mvc-demo:$VERSION
    - name: Push The Image
      run: |
        VERSION=${{ steps.vars.outputs.version }}
        docker push docker.io/${{ vars.DOCKER_USERNAME }}/mvc-demo:$VERSION
